parameters:
  prometheus:
    server:
      target:
        kubernetes:
          enabled: true
          api_ip: ${_param:kubernetes_control_address}
          ssl_dir: ${_param:prometheus_server_config_directory}
          cert_name: prometheus-server.crt
          key_name: prometheus-server.key
