
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.l1_support
- system.openssh.server.team.l2_support
- system.rsyslog.client.single
- cluster.k8s.kubernetes
parameters:
  _param:
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 10.0.1.15
    infra_config_deploy_address: 10.0.0.15

    cluster_domain: k8s.local
    cluster_name: k8s
    cluster_public_host: ${_param:openstack_proxy_address}
    control_vlan: 10
    tenant_vlan: 20

    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 10.0.0.1


  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
