parameters:
  salt:
    minion:
      cert:
        prometheus_server:
          host: ${_param:salt_minion_ca_host}
          authority: ${_param:salt_minion_ca_authority}
          key_file: ${prometheus:server:dir:config}/prometheus-server.key
          cert_file: ${prometheus:server:dir:config}/prometheus-server.crt
          common_name: prometheus-server
          signing_policy: cert_client
          alternative_names: IP:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
          mode: '0444'
